version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=tinkerbell
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     # - "cluster.routing.allocation.disk.watermark.low=30gb"
     # - "cluster.routing.allocation.disk.watermark.high=25gb"
     # - "cluster.routing.allocation.disk.watermark.flood_stage=20gb"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ekx
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch2
    environment:
      - cluster.name=tinkerbell
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    #  - "cluster.routing.allocation.disk.watermark.low=25gb"
    #  - "cluster.routing.allocation.disk.watermark.high=20gb"
    #  - "cluster.routing.allocation.disk.watermark.flood_stage=15gb"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - ekx
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    container_name: kibana
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - server.name=AnxMods
    ports:
      - 5601:5601
    networks:
      - ekx
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  ekx:
