version: "3.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    environment:
      - cluster.name=tinkerbell
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     # - "cluster.routing.allocation.disk.watermark.low=30gb"
     # - "cluster.routing.allocation.disk.watermark.high=25gb"
     # - "cluster.routing.allocation.disk.watermark.flood_stage=20gb"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
    - index

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - server.name=AnxMods
    ports:
      - 5601:5601
    networks:
    - index

  runtime:
    image: durson/tinkerbell:dev
    depends_on:
      - elasticsearch
      - elasticsearch2
    command: >
      /bin/sh -c "python3 runtime/redditstream.py --subreddit anxiety"
    networks:
    - index
    environment:
      REDDIT_AUTHENTICATION_DATA: /run/secrets/
    secrets:
    - reddit_auth

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  vault:
    driver: local
  consul:
    driver: local

networks:
  index:

secrets:
  reddit_auth:
    file: ./reddit_auth.json
