version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
    - cluster.name=snoowatch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - network.host=0.0.0.0
    - discovery.zen.ping.unicast.hosts=elasticsearch
    - discovery.zen.minimum_master_nodes=1
    - node.max_local_storage_nodes=50
    - xpack.monitoring.collection.enabled=true
    volumes:
    - snoodata:/usr/share/elasticsearch/data
    networks:
    - index

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
    - elasticsearch.url=http://elasticsearch-lb:9200
      - server.name=AnxMods
    ports:
      - 5601:5601
    networks:
    - index

  elasticsearch-lb:
    image: tnkinx:dev
    command: >
      /bin/bash -c "/usr/local/bin/wait-for-it.sh elasticsearch:9200 -- nginx -g 'daemon off;'"
    ports:
    - 9200:9200
    networks:
    - index

  runtime:
    image: durson/snoowatch:dev
    command: >
      /bin/sh -c "python3 redditstream.py --subreddit anxiety"
    networks:
    - index
    environment:
      REDDIT_AUTHENTICATION_DATA: /run/secrets/
    secrets:
    - reddit_auth

volumes:
  snoodata:
    driver: local

networks:
  index:

secrets:
  reddit_auth:
    file: ./reddit_auth.json
