version: "3.3"
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
    - cluster.name=snoowatch
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - node.max_local_storage_nodes=50
    - xpack.monitoring.collection.enabled=true
    volumes:
    - snoodata:/usr/share/elasticsearch/data
    networks:
      - snoowatch

  elasticsearch-slave:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
    environment:
      - cluster.name=snoowatch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch-master
      - discovery.zen.minimum_master_nodes=1
      - node.max_local_storage_nodes=50
      - xpack.monitoring.collection.enabled=true
    volumes:
      - snoodata:/usr/share/elasticsearch/data
    networks:
      - snoowatch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-lb:9200
      - SERVER_NAME=snoowatch
    ports:
      - 5601:5601
    networks:
      - snoowatch

  elasticsearch-lb:
    image: tnkinx:dev
    command: >
      /bin/bash -c "/usr/local/bin/wait-for-it.sh elasticsearch-master:9200 -- nginx -g 'daemon off;'"
    ports:
    - 9200:9200
    networks:
      - snoowatch

  runtime:
    image: durson/snoowatch:dev
    command: >
      /bin/sh -c "python3 redditstream.py --subreddit anxiety"
    networks:
      - snoowatch
    environment:
      REDDIT_AUTHENTICATION_DATA: /run/secrets/
    secrets:
    - reddit_auth

volumes:
  snoodata:
    driver: local

networks:
  snoowatch:

secrets:
  reddit_auth:
    file: ./reddit_auth.json
