version: "3"
services:
  consul:
    command: agent -server -http-port 8500 -ui -bind='{{ GetInterfaceIP "eth1" }}' -client 0.0.0.0 -bootstrap-expect=1
    image: consul:latest
    volumes:
      - consul:/consul/config
    ports:
      - 9301:9301
      - 8500:8500
      - 9600:9600/udp
    networks:
      - secrets

  vault:
    image: vault
    ports:
      - 8201:8201
      - 8200:8200
    networks:
      - secrets
    volumes:
    - vault:/mnt/vault-store/config
    - vault:/mnt/vault-store/data
    - vault:/mnt/vault-store  /logs
    depends_on:
      - consul
    environment:
    - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:8500","path":"vault"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}},"disable_mlock":"true"}
    - SKIP_SETCAP="true"
    command: server

volumes:
  vault:
    driver: local
  consul:
    driver: local

networks:
  secrets:
    driver: overlay